package dev.snowz.ormlitemigrator;

import com.j256.ormlite.field.DataType;
import com.j256.ormlite.field.DatabaseField;
import dev.snowz.ormlitemigrator.exception.DataTypeInvalidException;

import java.util.Date;

public class IncomingDatabaseFieldType {
    private final String fieldName;
    private final DatabaseField databaseField;
    private final Class type;

    public DatabaseField getDatabaseField() {
        return databaseField;
    }

    public String getFieldName() {
        return fieldName;
    }

    public IncomingDatabaseFieldType(final String fieldName, final DatabaseField databaseField, final Class tClass) {
        this.fieldName = fieldName;
        this.databaseField = databaseField;
        this.type = tClass;
    }

    public String generateStatement(final Database.Type databaseType) {
        String field = "";
        final String dataType = "";

        if (databaseField == null) {
            return "";
        }


        if (databaseField.dataType() == DataType.UNKNOWN) {
            if (this.getFieldClass().equals(String.class)) {
                field = "VARCHAR(255)";
            } else if (this.getFieldClass().equals(Integer.class) || this.getFieldClass().equals(int.class)) {
                if (databaseType == Database.Type.SqlLite) {
                    field = "INTEGER";
                } else if (databaseType == Database.Type.Postgres) {
                    field = "INTEGER";
                } else if (databaseType == Database.Type.H2) {
                    field = "INTEGER";
                } else {
                    field = "BIGINT(20)";
                }
            } else if (this.getFieldClass().equals(Boolean.class) || this.getFieldClass().equals(boolean.class)) {
                if (databaseType == Database.Type.Postgres) {
                    field = "BOOLEAN";
                } else {
                    field = "TINYINT(1)";
                }
            } else if (this.getFieldClass().equals(Date.class)) {
                if (databaseType == Database.Type.Postgres) {
                    field = "TIMESTAMP";
                } else {
                    field = "DATETIME";
                }
            } else {
                try {
                    throw new DataTypeInvalidException();
                } catch (final DataTypeInvalidException e) {
                    e.printStackTrace();
                }

                field = "VARCHAR(255)";
            }
        } else if (databaseField.dataType() == DataType.LONG_STRING) {
            field = "TEXT";
        } else {
            field = databaseField.dataType().getDataPersister().getSqlOtherType();
        }

        boolean isNotNull = false;
        boolean isAutoIncrementing = false;

        if (databaseField != null) {
            if (!databaseField.canBeNull()) {
                isNotNull = true;
            }

            if (databaseField.generatedId()) {
                isAutoIncrementing = true;
            }

        }

        String fieldCommand = this.getFieldName() + " " + field;

        if (isNotNull) {
            fieldCommand = fieldCommand + " NOT NULL";
        }

        if (isAutoIncrementing) {
            if (databaseType == Database.Type.SqlLite) {
                // SQLite requires INTEGER PRIMARY KEY for auto increment
            } else if (databaseType == Database.Type.Postgres) {
                // Postgres uses SERIAL or GENERATED BY DEFAULT AS IDENTITY
                // If we use SERIAL, it replaces the type.
                // If we use GENERATED BY DEFAULT, it is appended.
                // For simplicity, let's assume we are replacing the type with SERIAL if it's an integer ID.
                // But here we already defined 'field' as INTEGER.
                // We should probably change 'field' to SERIAL if it is auto incrementing integer.
                // However, this method constructs the string.
                // Let's do a quick fix:
                if (field.equals("INTEGER")) {
                    fieldCommand = this.getFieldName() + " SERIAL";
                    if (isNotNull) {
                        // SERIAL implies NOT NULL
                    }
                }
            } else {
                fieldCommand = fieldCommand + " AUTO_INCREMENT";
            }
        }

        return fieldCommand;
    }

    @Override
    public String toString() {
        return "IncomingDatabaseFieldType{" +
            "fieldName='" + fieldName + '\'' +
            ", databaseField=" + databaseField +
            '}';
    }

    public Class getFieldClass() {
        return type;
    }
}
